import React from "react"
import Head from "next/head"
import styles from "../styles/Home.module.scss"
import axios from "axios"
import Navbar from "../components/Navbar"
import { signIn, signOut, useSession } from "next-auth/client"
import { useAuth } from "../components/hooks"

function Home({ posts }) {
  const [session, loading] = useAuth()
  return (  
    <React.Fragment>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Nextjs-Django(Django-rest-framework)</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Navbar />
        <div className={styles.text}>
          <h1>Hello Mutherfucker</h1>
          <p>Ini berasal dari api, susah loh: {posts.name}, {posts.age}, {posts.blood}</p>
        </div>
        {
          loading && <h2 style={{textAlign: "center", fontSize: "20px"}}>Loading...</h2>
        }
        {!loading && !session && (
          <React.Fragment>
            Not signed in <br />
            <button onClick={() => signIn()} style={{fontSize: "20px"}}>Sign in</button>
            <pre style={{textAlign: "center", fontSize: "20px"}}>{!session && "User is not logged in"}</pre>
          </React.Fragment>
        )}
        {!loading && session && (
          <React.Fragment>
            Welcome {session.user.name} <br />
            <button onClick={() => signOut()} style={{ fontSize: "20px"}}>Sign out</button>
            {session.accessToken && (
            <pre style={{textAlign: "center", fontSize: "20px"}}>User has access token</pre>
            )}
          </React.Fragment>
        )}
      </div>
    </React.Fragment>
  )
}

export async function getStaticProps() {
  const res = await axios.get("http://127.0.0.1:3000/api/hello")
  const posts = await res.data

  return {
    props: {
      posts,
    }
  }
}

export default Home
